# Generated by Django 3.1 on 2020-08-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('in_couple_words', models.CharField(max_length=300)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=2)),
                ('descriptors', models.CharField(choices=[('001', 'Happy'), ('002', 'Productive'), ('003', 'Energetic'), ('004', 'Active'), ('005', 'Silly'), ('006', 'Content'), ('007', 'Motivated'), ('008', 'Joyful'), ('009', 'Focused'), ('101', 'Calm'), ('102', 'Average'), ('103', 'Uneventful'), ('201', 'Sad'), ('202', 'Depressed'), ('203', 'Anxious'), ('204', 'Numb'), ('205', 'Tired'), ('206', 'Irritable'), ('207', 'Lazy'), ('208', 'Insecure'), ('209', 'Cloudy')], max_length=3)),
            ],
        ),
    ]
