# Generated by Django 3.1 on 2020-08-23 01:13

import diary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('date', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
                ('in_couple_words', models.CharField(max_length=300)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('descriptors', models.JSONField(default=diary.models.default_descriptors)),
            ],
        ),
    ]
