# Generated by Django 3.1 on 2020-08-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200818_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='descriptors',
            field=models.JSONField(default='None'),
        ),
    ]
