# Generated by Django 3.1 on 2020-08-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20200819_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='descriptors',
            field=models.JSONField(default=list),
        ),
    ]
